// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Melody Nicholls",
            "email": "melody@technode.uk"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/checkout": {
            "get": {
                "description": "Returns the total value of the checkout including discounts",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "checkout"
                ],
                "summary": "Get the total of the checkout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorRes"
                        }
                    }
                }
            }
        },
        "/checkout/scan/{sku}": {
            "post": {
                "description": "Scans an item by it's provided SKU",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "checkout"
                ],
                "summary": "Scan an item",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SKU",
                        "name": "sku",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorRes"
                        }
                    }
                }
            }
        },
        "/discount/{sku}": {
            "post": {
                "description": "Scans an item by it's provided SKU",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "discount"
                ],
                "summary": "Creates or Updates a discount by it's provided SKU",
                "parameters": [
                    {
                        "type": "string",
                        "description": "SKU",
                        "name": "sku",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "The data for the discount you'd like to apply",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.CreateOrUpdateDiscountReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorRes"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.CreateOrUpdateDiscountReq": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "handlers.ErrorRes": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:4000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "ThinkMoney technical test",
	Description:      "This is an example repository for the technical test of think money",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
